import { localize, profile } from './data/base.mjs';
export const escape = value => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
const words = {
  en: { summary: 'Professional Summary', skills: 'Technical Skills', experience: 'Experience', training: 'Software Development Training', additional: 'Additional Training', projects: 'Selected Projects', education: 'Education', languages: 'Languages', developing: 'Currently developing', source: 'Source', review: 'Validated PR', home: 'Portfolio', print: 'Print / Save PDF', skip: 'Skip to main content' },
  'pt-PT': { summary: 'Resumo Profissional', skills: 'Competências Técnicas', experience: 'Experiência', training: 'Formação em Software Development', additional: 'Formação Complementar', projects: 'Projetos Selecionados', education: 'Educação', languages: 'Idiomas', developing: 'Em desenvolvimento', source: 'Código', review: 'PR validada', home: 'Portfolio', print: 'Imprimir / Guardar PDF', skip: 'Saltar para o conteúdo principal' }
};
export function cvContent(variant, lang) {
  const p = localize(profile, lang), w = words[lang];
  const section = (id, title, content) => `<section id="${id}" aria-labelledby="${id}-heading"><h2 id="${id}-heading">${title}</h2>${content}</section>`;
  const summary = variant.summary ? localize(variant.summary, lang) : variant.company ? `${lang === 'en' ? 'Development focus' : 'Foco de desenvolvimento'}: ${variant.emphasis}. ${p.summary}` : p.summary;
  return `<div class="cv-page cv-page-one">
    ${section('intro-section', w.summary, `<p>${escape(summary)}</p>`)}
    ${section('skills-col', w.skills, `<dl class="skill-list">${variant.skills.map(id => `<div data-skill-id="${id}"><dt>${escape(variant.skillTitles?.[id] ? localize(variant.skillTitles[id], lang) : p.skills[id].title)}</dt><dd>${escape([...(variant.skillPrefixes?.[id] || []), ...(variant.skillOrder?.[id] ? variant.skillOrder[id].map(n => p.skills[id].items[n]) : p.skills[id].items)].join(' · '))}</dd></div>`).join('')}</dl><p class="developing"><strong>${w.developing}:</strong> ${escape(p.training.developing)}</p>`)}
    ${section('experience-col', w.experience, p.experience.map((job, index) => `<article class="item" data-experience-id="${job.id}"><header><h3>${escape(job.role)}${job.organisation ? ` — ${escape(job.organisation)}` : ''}</h3><span class="when">${escape(job.dates)}</span></header><ul>${(index === 0 ? variant.experienceBullets.map(n => job.bullets[n]) : job.bullets).map(bullet => `<li>${escape(bullet)}</li>`).join('')}</ul></article>`).join(''))}
  </div><div class="cv-page cv-page-two">
    ${section('training-col', w.training, `<article class="item"><h3>Software Developer</h3><p>${escape(p.training.description)}</p></article><article class="item"><h3>${escape(p.completedTraining.title)}</h3><p>${escape(p.completedTraining.provider)}</p><p>${escape(p.completedTraining.description)}</p></article>`)}
    ${section('projects-col', w.projects, variant.projects.map(id => { const project = p.projects[id]; return `<article class="item" data-project-id="${id}"><h3>${escape(project.name)} <span class="project-tech">${escape(project.stack.join(' · '))}</span></h3><p>${escape(variant.projectDescriptions?.[id] ? localize(variant.projectDescriptions[id], lang) : project.short)}</p><p class="project-links"><a href="${project.repo}" target="_blank" rel="noopener">${w.source}: ${escape(project.repo.replace('https://github.com/', 'github.com/'))}</a>${project.review ? ` · <a href="${project.review}" target="_blank" rel="noopener">${w.review} #53</a>` : ''}</p></article>`; }).join(''))}
    ${section('courses-col', w.additional, `<p>${escape(p.additionalTraining)}</p>`)}
    ${section('education-col', w.education, `<ul>${p.education.map(item => `<li>${escape(item)}</li>`).join('')}</ul>`)}
    ${section('languages-col', w.languages, `<p>${escape(p.languages)}</p>`)}
  </div>`;
}
export function cvPage(id, variant) {
  const root = id === 'master' ? '../' : '../../../';
  const canonical = `${profile.links.portfolio.replace('home/', '')}${id === 'master' ? 'resume-site-only/' : `resume/variants/${id}/`}`;
  const contents = Object.fromEntries(['en', 'pt-PT'].map(lang => [lang, cvContent(variant, lang)]));
  const payload = JSON.stringify({ contents, title: profile.title, variant: id }).replace(/</g, '\\u003c');
  const description = 'Daniela Torres Almeida — Software Developer / Front-End Developer in training. React, TypeScript, Java and Spring Boot. Curricular internship scheduled 1 March - 20 May 2027.';
  return `<!doctype html>
<!-- Generated by scripts/build-resumes.mjs. Edit resume/data, resume/variants or resume/render.mjs. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Daniela Torres Almeida | ${variant.company ? escape(variant.company) + ' — ' : ''}Software Developer CV</title>
<meta name="description" content="${description}">${id !== 'master' ? '<meta name="robots" content="noindex,nofollow">' : ''}
<link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:title" content="Daniela Torres Almeida | Software Developer CV"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="https://danielatorresalmeida.github.io/Portfolio-website/assets/logo_portfolio.png"><meta property="og:image:alt" content="Daniela Torres Almeida portfolio logo"><meta name="twitter:card" content="summary">
<link rel="icon" href="${root}assets/logo_portfolio.png"><link rel="stylesheet" href="${root}resume/shared/cv.css?v=__ASSET_VERSION__">
</head><body data-variant="${id}"><a class="skip-link" href="#main-content">Skip to main content</a>
<header class="topbar"><div class="container"><div class="identity"><h1>Daniela Torres Almeida</h1><p id="professional-title">${profile.title.en}</p><p class="meta">Cascais / Lisbon area, Portugal</p><nav class="contact-links" aria-label="Professional links"><a href="${profile.links.portfolio}">Portfolio</a><a href="${profile.links.github}" target="_blank" rel="noopener">GitHub</a><a href="${profile.links.linkedin}" target="_blank" rel="noopener">LinkedIn</a><button type="button" class="contact-reveal" data-contact-reveal="email" aria-label="Reveal email address">Reveal email</button><button type="button" class="contact-reveal" data-contact-reveal="phone" aria-label="Reveal phone number">Reveal phone</button></nav></div><div class="actions"><button id="print-btn" type="button" aria-label="Download CV">Print / Save PDF</button><button id="lang-toggle" type="button" aria-label="Switch language to European Portuguese"><span class="pill-label">PT-PT</span></button><button id="theme-toggle" type="button" aria-label="Switch to light theme" aria-pressed="true">Light theme</button><a class="home-btn" href="${root}index.html#home">Portfolio</a></div></div></header>
<main id="main-content" class="container resume"><div id="cv-content">${contents.en}</div></main>
<footer class="container footer"><p>Daniela Torres Almeida · Software Development CV</p></footer>
<script id="cv-data" type="application/json">${payload}</script><script src="${root}resume-site-only/script.js?v=__ASSET_VERSION__" defer></script><script src="${root}assets/contact-reveal.js?v=__ASSET_VERSION__" defer></script></body></html>\n`;
}
